version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_ROOT: postgres
      POSTGRES_PASSWORD: password
    command: -c fsync=off -c shared_buffers=2048MB -c full_page_writes=off
    ports:
      - "56001:5432"
